[package]
name = "rust_game"
version = "0.1.0"
edition = "2021"

[dependencies]

winit = "0.29"
wgpu = "23.0"
log = "0.4.22"
env_logger = "0.10"
pollster = "0.3"
bytemuck = { version = "1.16", features = ["derive"]}
image = { version = "0.24", default_features = false, features = ["png", "jpeg"]}
